### PR TITLE
Introduce TransactionSelectionContext to pass data between selectors and plugin

### PR DESCRIPTION
**Pull request by fab-10**
Some tx selector plugins needs more context about the current tx being evaluated, for example the current minGasPrice, or the effective price of the tx and possibly more data in the future, for this we introduce the `TransactionSelectionContext` to hold that data and pass it across all the selectors and the plugin. Another advantage of this context is to avoid to compute multiple time the same data, in case it is needed in more that one selector.

This PR will be ported to main Besu repo as well.

### CODE REVIEW

**Comment by Gabriel-Trintinalia** [comment]
lgtm, does it make sense to have `onTransactionSelected` and `onTransactionNotSelected` also passing the `TransactionEvaluationContext` instead of `PendingTransaction` so that plugins can handle the events with the same information that performed the evaluation?

**Comment by fab-10** [comment]
@Gabriel-Trintinalia good suggestion, will pass the context to those method too

**Comment by Filter94** [comment]
Will we be able to get RLP encoded transaction size in the plugin, without it being a part of the new context?

**Comment by fab-10** [comment]
> Will we be able to get RLP encoded transaction size in the plugin, without it being a part of the new context?

that information is already provided by `Transaction::getSize`

**Comment by fab-10** [comment]
I am merging this since all the comments have been resolved and it is needed to unblock the plugin side. 
I will open the same PR on main Besu repo so if you still have feedback you can add there.

**Pull request merged**
